Kami
eniJohnny/rt pull request #12
Opened 2024-04-11 13:42 UTC by kamiakze69j

Finished parsing
Added shapes, lights, and camera plus their accessors and constructors
Added GUI mod to handle the gui
Added Event mod to handle window events
Changed window for Nannou::Sketch to Nannou::App (to handle events)
Cleaned main.rs
Changed scene.json's location (scene/scene.json) and contents (pos, dir and color are now Vec3, Vec3 and [u8; 3])

2024-04-11 15:21 UTC, eniJohnny commented on src/model/materials/unicolor.rs
Au final, my bad, selon moi il vaudrait moi avoir un new qui prend du r g et b, et simplement utiliser #derive[Clone] pour avoir la fonction.clone(color: Color) automatiquement

2024-04-11 15:51 UTC, eniJohnny commented on src/model/objects/camera.rs
> +    pub fn get_dir(&self) -> Vec3 { Vec3::new(self.dir.x().to_owned(), self.dir.y().to_owned(), self.dir.z().to_owned()) }
Alors dans l'idee si tu veux un getter tu renvoies une reference &Vec3. Si tu veux copier ce vecteur, tu as juste a appeler .clone() sur le &Vec3 que tu recuperes (on l'a implemente dans la derniere PR).
Tu auras surement besoin d'un setter aussi je pense, avec les translations/rotation du gui.
D'une maniere generale on renverra toujours une reference (&) pour nos getters, et si besoin de modification, on ajoutera un setter.
pub fn pos(&self) -> &Vec3 {
    &self.pos
}

pub fn set_pos(&mut self, pos: Vec3) {
    self.pos = pos;
}

2024-04-11 15:52 UTC, eniJohnny commented on src/model/objects/camera.rs
> +    pub fn get_dir(&self) -> Vec3 { Vec3::new(self.dir.x().to_owned(), self.dir.y().to_owned(), self.dir.z().to_owned()) }
Si tu pouvais voir ca pour tous les getters que tu as fait s'il te plait

2024-04-11 15:52 UTC, eniJohnny commented on src/model/objects/light.rs
> +    pub fn get_pos(&self) -> Vec3 { Vec3::new(self.pos.x().to_owned(), self.pos.y().to_owned(), self.pos.z().to_owned()) }
A revoir

2024-04-11 15:55 UTC, eniJohnny commented on src/model/mod.rs
> +}
A supprimer vu que ca a ete deplace dans scene.rs

2024-04-11 15:57 UTC, eniJohnny commented on src/lib.rs
> +pub const SCREEN_HEIGHT: u32 = 900;
Pas besoin de le mettre en pub non ? S'il est const il sera disponible partout

2024-04-11 15:57 UTC, RuBeeN-cmd requested changes
Changer les getters, juste renvoyer une reference

2024-04-11 15:57 UTC, RuBeeN-cmd commented on src/render/mod.rs
> +// }
??????

2024-04-11 15:57 UTC, RuBeeN-cmd commented on src/model/objects/camera.rs
> +    pub fn get_dir(&self) -> Vec3 { Vec3::new(self.dir.x().to_owned(), self.dir.y().to_owned(), self.dir.z().to_owned()) }
Yes un peu degueu les `to_owned()` et mets sur plusieurs lignes

2024-04-11 16:00 UTC, eniJohnny commented on src/model/objects/camera.rs
> -        unimplemented!()
Pourquoi tu as supprime cette fonction ?

2024-04-11 16:05 UTC, eniJohnny commented on src/parsing/mod.rs
> +        let end = remaining.find("\n    }").unwrap() + 6;
Je dis ca ici mais ca vaut pour tous les unwrap que tu as utilise. Unwrap panique et crash le programme si tu l'appeles sur None. Si c'est le comportement que tu veux, utilise plutot `.expect("Message d'erreur")` qui fait la meme chose avec un message d'erreur contextuel.

2024-04-11 16:10 UTC, eniJohnny commented on src/render/mod.rs
> +pub fn display_scene(scene: &Scene) {
- Du coup comme on en a discute, le render ca va etre pour le processing, pour la gestion du gui du as ton module gui dans lquelle tu mettras la gestion du display.
- Egalement, fais gaffe parce que pendant les merges de ton rebase tu as supprime tout le code que j'avais fait pour le render sans le mettre autre part. Si tu pouvais stp le remettre ou il etait dans render/mod.rs, et deplacer tes events et le display dans un seule module gui, je pense que ca pourrait etre pas mal

2024-04-12 07:09 UTC, kamiakze69j commented on src/model/materials/unicolor.rs
Done!

2024-04-12 07:12 UTC, kamiakze69j commented on src/model/objects/camera.rs
> +    pub fn get_dir(&self) -> Vec3 { Vec3::new(self.dir.x().to_owned(), self.dir.y().to_owned(), self.dir.z().to_owned()) }
Done!

2024-04-12 07:12 UTC, kamiakze69j commented on src/model/objects/light.rs
> +    pub fn get_pos(&self) -> Vec3 { Vec3::new(self.pos.x().to_owned(), self.pos.y().to_owned(), self.pos.z().to_owned()) }
Done!

2024-04-12 07:13 UTC, kamiakze69j commented on src/model/mod.rs
> +}
Oops, done!

2024-04-12 07:15 UTC, kamiakze69j commented on src/lib.rs
> +pub const SCREEN_HEIGHT: u32 = 900;
Done!

2024-04-12 07:16 UTC, kamiakze69j commented on src/render/mod.rs
> +// }
J'avais pas le get_rays de johnny

2024-04-12 07:17 UTC, kamiakze69j commented on src/model/objects/camera.rs
> -        unimplemented!()
Unintentional, mb.

2024-04-12 07:37 UTC, kamiakze69j commented on src/parsing/mod.rs
> +        let end = remaining.find("\n    }").unwrap() + 6;
le unwrap me semble necessaire apres un get, find, split, parse etc, si tu vois une autre facon je suis preneneur. En attendant, je vire les get(), ca permet de virer un unwrap

2024-04-12 07:46 UTC, kamiakze69j commented on src/render/mod.rs
> +pub fn display_scene(scene: &Scene) {
J'ai cree display/mod.rs pour le display de la fenetre qui ne concerne pas le GUI

2024-04-12 11:21 UTC, eniJohnny approved these changes
Parfait ca me va

2024-04-12 12:17 UTC, eniJohnny commented
PR fermee, on a recree une branche clean_kami a partir de main sur laquelle on a merge kami pour envoyer plus proprement

2024-04-12 12:17 UTC, closed without merging